<?php

use Illuminate\database\Seeder;
use WebCondom\Models\Financeiros\ContaCorrenteLancamento;

class ContasCorrentesLancamentosSeeder extends Seeder
{
    public function run()
    {
        $dados = [
            [
                'nota_fiscal' => '',
                'parcela' => '',
                'data_lancamento' => '2015-12-31',
                'documento' => '',
                'tipo' => '2',
                'historico' => 'SALDO INICIAL',
                'valor' => '58000.00',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '16',
                'conta_corrente_id' => '12'
            ],
            [
                'nota_fiscal' => '',
                'parcela' => '',
                'data_lancamento' => '2017-12-31',
                'documento' => '',
                'tipo' => '1',
                'historico' => 'SALDO INICIAL',
                'valor' => '2000.00',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '16',
                'conta_corrente_id' => '11'
            ],
            [
                'nota_fiscal' => '000123456',
                'parcela' => '01',
                'data_lancamento' => '2018-01-05',
                'documento' => '100211',
                'tipo' => '1',
                'historico' => 'ELEVADORES OTIS',
                'valor' => '236.67',
                'compensado' => '1',
                'cheque' => '1',
                'plano_conta_id' => '10',
                'conta_corrente_id' => '11',
                'fornecedor_id' => '1'
            ],
            [
                'nota_fiscal' => '',
                'parcela' => '',
                'data_lancamento' => '2018-02-08',
                'documento' => '',
                'tipo' => '1',
                'historico' => 'COMPRA DE MATERIAL LIMPEZA',
                'valor' => '90',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '12',
                'conta_corrente_id' => '11'
            ],
            [
                'nota_fiscal' => '000000555',
                'parcela' => '01',
                'data_lancamento' => '2018-02-10',
                'documento' => '100212',
                'tipo' => '1',
                'historico' => 'ELEVADORES ATLAS',
                'valor' => '150',
                'compensado' => '1',
                'cheque' => '1',
                'plano_conta_id' => '10',
                'conta_corrente_id' => '11',
                'fornecedor_id' => '1'
            ],
            [
                'data_lancamento' => '2018-02-11',
                'documento' => '002',
                'tipo' => '2',
                'historico' => 'LIQ.DE COBRANCA',
                'valor' => '3169',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '1',
                'conta_corrente_id' => '11'
            ],
            [
                'data_lancamento' => '2018-02-11',
                'documento' => '',
                'tipo' => '1',
                'historico' => 'TAXA DE ADM.',
                'valor' => '937',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '9',
                'conta_corrente_id' => '11',
            ],
            [
                'nota_fiscal' => '000001999',
                'parcela' => '02',
                'data_lancamento' => '2018-02-20',
                'documento' => '100215',
                'tipo' => '1',
                'historico' => 'PRODUTOS DE LIMPEZA',
                'valor' => '225',
                'compensado' => '1',
                'cheque' => '1',
                'plano_conta_id' => '12',
                'conta_corrente_id' => '11',
                'fornecedor_id' => '1'
            ],
            [
                'data_lancamento' => '2018-02-20',
                'documento' => '999888',
                'tipo' => '1',
                'historico' => 'CONTA DE LUZ',
                'valor' => '868.27',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '7',
                'conta_corrente_id' => '11'
            ],
            [
                'data_lancamento' => '2018-02-12',
                'documento' => '002',
                'tipo' => '2',
                'historico' => 'LIQ.DE COBRANCA',
                'valor' => '2680',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '1',
                'conta_corrente_id' => '11'
            ],
            [
                'nota_fiscal' => '000002321',
                'parcela' => '01',
                'data_lancamento' => '2018-02-12',
                'documento' => '100215',
                'tipo' => '1',
                'historico' => 'EXTINTELE S.A.',
                'valor' => '197',
                'compensado' => '1',
                'cheque' => '1',
                'plano_conta_id' => '10',
                'conta_corrente_id' => '11',
                'fornecedor_id' => '2'
            ],
            [
                'nota_fiscal' => '000002000',
                'parcela' => '01',
                'data_lancamento' => '2018-02-10',
                'documento' => '100217',
                'tipo' => '1',
                'historico' => 'PRODUTOS DE LIMPEZA',
                'valor' => '211',
                'compensado' => '1',
                'cheque' => '1',
                'plano_conta_id' => '12',
                'conta_corrente_id' => '11',
                'fornecedor_id' => '1'
            ],
            [
                'data_lancamento' => '2018-02-10',
                'documento' => '002',
                'tipo' => '2',
                'historico' => 'LIQ.DE COBRANCA',
                'valor' => '3000',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '1',
                'conta_corrente_id' => '11'
            ],
            [
                'data_lancamento' => '2018-02-08',
                'documento' => '',
                'tipo' => '1',
                'historico' => 'TAXA DE ADM.',
                'valor' => '937',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '9',
                'conta_corrente_id' => '11',
            ],
            [
                'nota_fiscal' => '000202020',
                'parcela' => '01',
                'data_lancamento' => '2018-02-25',
                'documento' => '100218',
                'tipo' => '1',
                'historico' => 'PRODUTOS DE LIMPEZA',
                'valor' => '36.79',
                'compensado' => '1',
                'cheque' => '1',
                'plano_conta_id' => '12',
                'conta_corrente_id' => '11',
                'fornecedor_id' => '1'
            ],
            [
                'data_lancamento' => '2018-02-10',
                'documento' => '',
                'tipo' => '1',
                'historico' => 'CONTA DE AGUA E ESGOTO',
                'valor' => '133',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '8',
                'conta_corrente_id' => '11'
            ],
            [
                'data_lancamento' => '2018-02-28',
                'documento' => '002',
                'tipo' => '2',
                'historico' => 'LIQ.DE COBRANCA',
                'valor' => '1000',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '1',
                'conta_corrente_id' => '11'
            ],
            [
                'nota_fiscal' => '000123499',
                'parcela' => '01',
                'data_lancamento' => '2018-02-11',
                'documento' => '100219',
                'tipo' => '1',
                'historico' => 'CLORO PARA PISCINA',
                'valor' => '353',
                'compensado' => '1',
                'cheque' => '1',
                'plano_conta_id' => '11',
                'conta_corrente_id' => '11',
                'fornecedor_id' => '1'
            ],
            [
                'data_lancamento' => '2018-02-25',
                'documento' => '',
                'tipo' => '1',
                'historico' => 'SALARIO FUNCIONARIOS',
                'valor' => '5322.90',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '4',
                'conta_corrente_id' => '11'
            ],
            [
                'nota_fiscal' => '000000500',
                'parcela' => '01',
                'data_lancamento' => '2018-02-23',
                'documento' => '100220',
                'tipo' => '1',
                'historico' => 'MANUTENCAO SISTEMA CONDOM',
                'valor' => '880',
                'compensado' => '1',
                'cheque' => '1',
                'plano_conta_id' => '14',
                'conta_corrente_id' => '11',
                'fornecedor_id' => '3'
            ],
            [
                'data_lancamento' => '2018-02-28',
                'documento' => '',
                'tipo' => '1',
                'historico' => 'FERIAS E 13.SALARIO',
                'valor' => '1200.00',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '6',
                'conta_corrente_id' => '11'
            ],
            [
                'data_lancamento' => '2018-02-23',
                'documento' => '100222',
                'tipo' => '1',
                'historico' => 'TX DE ADM.',
                'valor' => '954',
                'compensado' => '1',
                'cheque' => '1',
                'plano_conta_id' => '9',
                'conta_corrente_id' => '11'
            ],
            [
                'data_lancamento' => '2018-02-23',
                'documento' => '002',
                'tipo' => '2',
                'historico' => 'LIQ.DE COBRANCA',
                'valor' => '5069',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '1',
                'conta_corrente_id' => '11'
            ],
            [
                'data_lancamento' => '2018-02-25',
                'documento' => '',
                'tipo' => '1',
                'historico' => 'TAXA DE ADM ',
                'valor' => '937',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '9',
                'conta_corrente_id' => '11',
            ],
            [
                'data_lancamento' => '2018-03-05',
                'documento' => '',
                'tipo' => '1',
                'historico' => 'SALARIO FUNCIONARIOS',
                'valor' => '4500.90',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '4',
                'conta_corrente_id' => '11'
            ],
            [
                'data_lancamento' => '2018-03-03',
                'documento' => '999666',
                'tipo' => '1',
                'historico' => 'CONTA DE LUZ - CPFL',
                'valor' => '763.77',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '7',
                'conta_corrente_id' => '11'
            ],
            [
                'data_lancamento' => '2018-03-03',
                'documento' => '002',
                'tipo' => '2',
                'historico' => 'LIQ.DE COBRANCA',
                'valor' => '2555',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '1',
                'conta_corrente_id' => '11'
            ],
            [
                'nota_fiscal' => '000055440',
                'parcela' => '01',
                'data_lancamento' => '2018-03-03',
                'documento' => '100225',
                'tipo' => '1',
                'historico' => 'RECARGA EXTINTOR.',
                'valor' => '349',
                'compensado' => '1',
                'cheque' => '1',
                'plano_conta_id' => '10',
                'conta_corrente_id' => '11',
                'fornecedor_id' => '2'
            ],
            [
                'nota_fiscal' => '000012000',
                'parcela' => '01',
                'data_lancamento' => '2018-03-10',
                'documento' => '100225',
                'tipo' => '1',
                'historico' => 'MATERIAL DE LIMPEZA',
                'valor' => '350',
                'compensado' => '1',
                'cheque' => '1',
                'plano_conta_id' => '12',
                'conta_corrente_id' => '11',
                'fornecedor_id' => '1'
            ],
            [
                'data_lancamento' => '2018-03-03',
                'documento' => '',
                'tipo' => '1',
                'historico' => 'FERIAS E 13.SALARIO',
                'valor' => '1750.00',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '6',
                'conta_corrente_id' => '11'
            ],
            [
                'nota_fiscal' => '000055445',
                'parcela' => '01',
                'data_lancamento' => '2018-02-10',
                'documento' => '1001',
                'tipo' => '1',
                'historico' => 'RECARGA EXTINTOR.',
                'valor' => '5000',
                'compensado' => '1',
                'cheque' => '1',
                'plano_conta_id' => '10',
                'conta_corrente_id' => '11',
                'fornecedor_id' => '2'
            ],
            [
                'nota_fiscal' => '000012009',
                'parcela' => '01',
                'data_lancamento' => '2018-03-08',
                'documento' => '100229',
                'tipo' => '1',
                'historico' => 'MATERIAL DE ESCRITORIO',
                'valor' => '176',
                'compensado' => '1',
                'cheque' => '1',
                'plano_conta_id' => '12',
                'conta_corrente_id' => '11',
                'fornecedor_id' => '1'
            ],
            [
                'data_lancamento' => '2018-02-08',
                'documento' => '002',
                'tipo' => '2',
                'historico' => 'LIQ.DE COBRANCA',
                'valor' => '8000',
                'compensado' => '1',
                'cheque' => '0',
                'plano_conta_id' => '1',
                'conta_corrente_id' => '11'
            ],
            [
                'data_lancamento' => '2018-01-31',
                'documento' => '002',
                'tipo' => '2',
                'historico' => 'LIQ.DE COBRANCA',
                'valor' => '3000',
                'compensado' => '2',
                'cheque' => '0',
                'plano_conta_id' => '1',
                'conta_corrente_id' => '11'
            ],
            [
                'data_lancamento' => '2018-02-01',
                'documento' => '',
                'tipo' => '1',
                'historico' => 'TAXA DE ADM ',
                'valor' => '1000',
                'compensado' => '2',
                'cheque' => '0',
                'plano_conta_id' => '9',
                'conta_corrente_id' => '11',
            ],

        ];
        foreach ($dados as $dado) {
            ContaCorrenteLancamento::create($dado);
        };
    }
}